### ISSUE TITLE
Toggle between webhook and polling during dev

### ISSUE THREAD

**Issue by jaxsax** [bananers/tapeworm-bot#1]
In order to dev the bot currently, we need to run an instance of the environment with gcloud sdk via `dev_appserver.py`. 

Changing this to detect any environment variables listed [here](https://cloud.google.com/appengine/docs/standard/python3/runtime), we can probably toggle between using a webhook and using getUpdates from telegram.

**Comment by xhan017** [comment]
Hey! Any updates on this? 🙂
